### ISSUE TITLE
Fix style in dark mode

### ISSUE THREAD

**Issue by gopi-suvanam** [gopi-suvanam/scribbler#21]
The app is looking ok in light mode, but in dark mode each cell has white border. it is not looking very clean. needs fixing.

**Comment by DH-ai** [comment]
How about Monokai or similar dark mode themes not only for dark mode but for the light mode too, with a toggle options and simple state transitions animations in css.

**Comment by gopi-suvanam** [comment]
Can you implement Monokai without having heavy footprint?

**Comment by DH-ai** [comment]
I may work on this issue in the future. Then, I will try.

**Comment by gopi-suvanam** [comment]
Thanks @DH-ai for fixing this.. it was helpful
