### ISSUE TITLE
changing on click color of navbar elements

### ISSUE THREAD

**Issue by jeevikasirwani** [gopi-suvanam/scribbler#22]
**Is your feature request related to a problem? Please describe.**
on clicking any navbar element it blends with the color of website itself so maybe using different color on click  example i clicked on tutorial 

![image](https://github.com/gopi-suvanam/scribbler/assets/83456541/cb71995b-158a-4995-853b-761733b5fbf2)

**Comment by gopi-suvanam** [comment]
hi this issue is with the website not the product. but needs to be fixed.. do you want to contribute to this? The repo for this is:
https://github.com/gopi-suvanam/scribbler-website

**Comment by jeevikasirwani** [comment]
> hi this issue is with the website not the product. but needs to be fixed.. do you want to contribute to this? The repo for this is: https://github.com/gopi-suvanam/scribbler-website

sure i can try

**Comment by gopi-suvanam** [comment]
thanks.. you can try to fix and send a pull request.. 

also look at the product: https://app.scibbler.live 

If you want to work on any issues there, let me know

**Comment by gopi-suvanam** [comment]
did you get a chance to look at it?

you can download the scribbler-website repo and open index.html  to test.. I think this is the section that needs changing:
https://github.com/gopi-suvanam/scribbler-website/blob/9eaeb3a30696b661e2db4d4194103a04bb8cc03c/assets/css/main.css#L1441

**Comment by jeevikasirwani** [comment]
> did you get a chance to look at it?
> 
> you can download the scribbler-website repo and open index.html to test.. I think this is the section that needs changing: https://github.com/gopi-suvanam/scribbler-website/blob/9eaeb3a30696b661e2db4d4194103a04bb8cc03c/assets/css/main.css#L1441

yes I have made the changes and created PR

**Comment by gopi-suvanam** [comment]
Can you make it blue color instead of black on hover/active to make it interesting? right now hover is looking plain.. you can use #0b0bee

**Comment by gopi-suvanam** [comment]
thanks for the contribution.. closing this issue now!

**Comment by gopi-suvanam** [comment]
hi.. Can you try to fix this issue :

https://github.com/gopi-suvanam/scribbler/issues/20
